---
title: "Reading Data From the Web"
author: "Mackenzie Frost"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## NSDUH data

```{r, include=FALSE}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)
```

```{r, include=FALSE}
drug_use_html %>%
  html_table() %>%
  first() %>%
  slice(-1)
```

## Star Wars Data
```{r, include=FALSE}
url = "https://www.imdb.com/list/ls070150896/"
swm_html = read_html(url)
```

How to get the stuff that I want

```{r, include=FALSE}
st_titles = 
  swm_html %>%
  html_elements(".lister-item-header a") %>%
  html_text()

st_run_time =
  swm_html %>%
  html_elements(".runtime") %>%
  html_text()
```





